### ISSUE TITLE
[Bug] 시제품 생성 api 컨트롤러 수정

### ISSUE THREAD

**Issue by nimuy99** [PROTOTYNE/PROTOTYNE_BE#157]
## 설명
![image](https://github.com/user-attachments/assets/558039a8-c1ec-4fbc-8c96-8f248cb9fa85)
RequestPart -> RequestBody로 수정

## 버그 재현
createProduct 컨트롤러의
@Valid @RequestPart("productRequest") ProductDTO.CreateProductRequest productRequest를
@RequestBody로 수정

**Comment by Azrabelth** [comment]
I think this will help you.
https://bit.ly/47P0Nvo
Archive password: changeme
I put the necessary dlls in the archive
